export const ERROR_CODES = [
  "INVALID_JSON",
  "INVALID_SCHEMA",
  "INVALID_SIGNATURE",
  "UNKNOWN_DEVICE",
  "PREKEY_BUNDLE_NOT_FOUND",
  "MAILBOX_NOT_FOUND",
  "CHALLENGE_EXPIRED",
  "RATE_LIMITED",
  "QUOTA_EXCEEDED",
  "PAYLOAD_TOO_LARGE",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
