export const LIMITS = {
  MAX_MESSAGE_BYTES: 262144, // 256 KB
  MAILBOX_TTL_HOURS: 168, // 7 days
  CHALLENGE_TTL_SECONDS: 60,
  PREKEY_MIN_COUNT: 20,
  PREKEY_REFILL_THRESHOLD: 10,
  MAX_MAILBOX_BATCH: 100,
} as const;
